In [3]:
import numpy as np  #NUMPY KÜTÜPHANESİNİ İMPORT ETTİK (np diye kullanabilirim artık)

In [6]:
my_list=[10,20,30,40] #python ile normal listemizi oluşturduk

In [7]:
type(my_list)

list

In [8]:
np.array(my_list) # --> numpy listesine dönüştürüyoruz burada

array([10, 20, 30, 40])

In [9]:
my_numpy_array=np.array(my_list)

In [11]:
type(my_numpy_array)  #ÇIKTIRI NUMPY ARRAY OLACAK

numpy.ndarray

In [14]:
my_list1=[1,2]

In [17]:
my_list2=[2,3]

In [19]:
my_list1+my_list2    #normal python dizilerde + işlemini yaptığımızda toplama yapmıyor ardına ekliyor

[1, 2, 2, 3]

In [20]:
my_numpy_array1 = np.array(my_list1)

In [21]:
my_numpy_array2 = np.array(my_list2)

In [23]:
my_numpy_array1 + my_numpy_array2   #görüğümüz üzere burada numpy arrayine çevirdiğimizden aynı indexteki elemanları topladı

array([3, 5])

In [24]:
my_numpy_array1 * my_numpy_array2   #görüğümüz üzere burada numpy arrayine çevirdiğimizden aynı indexteki elemanları çarptı

array([2, 6])

In [25]:
my_numpy_array1 - my_numpy_array2   #görüğümüz üzere burada numpy arrayine çevirdiğimizden aynı indexteki elemanları çıkarttı

array([-1, -1])

In [26]:
my_numpy_array1 / my_numpy_array2   #görüğümüz üzere burada numpy arrayine çevirdiğimizden aynı indexteki elemanları böldü

array([0.5       , 0.66666667])

In [28]:
my_numpy_array1 * 5

array([ 5, 10])

In [29]:
other_array=np.array([10,20,30,40,50])

In [41]:
print(other_array.min())

10


In [42]:
print(other_array.sum())

150


<center>
<img src="pic/ornekBir.png" width="900">
</center>

In [34]:
#iki diziyi biribiriyle aritmetik işleme sokacaksak boyutları aynı olmalı yoksa hata alırız

In [35]:
my_numpy_array1

array([1, 2])

In [36]:
other_array

array([10, 20, 30, 40, 50])

In [39]:
# my_numpy_array1 + other_array HATA VERİR CÜNKÜ UZUNLUKLARI BİRBİRİNDEN FARKLI

In [44]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
np_array=np.arange(0,10)

In [48]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
print(np_array[0])

0


In [52]:
print(np_array[-1])

9


In [53]:
print(np_array[1:4:])

[1 2 3]


In [55]:
np.random.randn(4) # array icinde 4 tane random sayı verir

array([-0.10762618, -1.36216327,  0.04300502, -0.71578089])

In [57]:
np.random.randn(4,4) #4x4 içinde random sayılar olan matris verir

array([[-1.18204588, -1.92238691,  0.72270892,  0.76528781],
       [ 0.64717375,  0.9498339 , -0.29114192, -0.03283394],
       [ 0.10783997,  0.28628896, -0.2285242 , -1.81243488],
       [-0.87805031,  0.13466652,  0.56762919, -0.55537012]])

In [59]:
np.random.randint(1,300,5) #1 ile 300 arasında bana 5 tane tam sayı verir

array([ 44,  68, 222, 120, 170])