In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([40, 59, 75, 16, 49, 35, 33, 47,  3, 94, 80, 19, 97, 56, 88, 28, 46,
       48, 80, 70])

In [4]:
new_array > 25

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
new_array[new_array > 25]

array([40, 59, 75, 49, 35, 33, 47, 94, 80, 97, 56, 88, 28, 46, 48, 80, 70])

In [6]:
##TRANSPOSE & RESHAPE

In [7]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [8]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [9]:
matrix_array.shape

(3, 2)

In [12]:
matrix_array.transpose()  #transpose aldı

array([[10, 20, 30],
       [20, 30, 40]])

In [13]:
matrix_array.T            #transpose aldı

array([[10, 20, 30],
       [20, 30, 40]])

In [14]:
random_array=np.random.random((6,1))

In [15]:
random_array

array([[0.74956693],
       [0.25617026],
       [0.11757924],
       [0.02384767],
       [0.73331758],
       [0.86057878]])

In [16]:
random_array.shape

(6, 1)

In [17]:
random_array.reshape(2,3)

array([[0.74956693, 0.25617026, 0.11757924],
       [0.02384767, 0.73331758, 0.86057878]])

In [18]:
#z-score

In [19]:
data = np.array([10,12,13,15,18,25,100,105])

In [21]:
#outlier(çıkıntı)

In [25]:
mean=np.mean(data)  #ortalama alıyor

In [26]:
mean

np.float64(37.25)

In [27]:
data.sum()/len(data)   #manuel ortalama alıyor

np.float64(37.25)

In [28]:
std = np.std(data)

In [29]:
std

np.float64(37.9333296719389)

In [30]:
z_score = (data-mean) / std

In [31]:
z_score

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [32]:
z_score > 1

array([False, False, False, False, False, False,  True,  True])

In [34]:
z_score[z_score > 1]

array([1.65421809, 1.78602829])

In [35]:
data[z_score > 1]

array([100, 105])